site_name: The Thinking Doer
site_url: https://nickydoes.demarcohome.com

theme:
  name: material
  font:
    text: Roboto Flex
    code: Red Hat Mono
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra:
  social:
    - icon: fontawesome/brands/creative-commons
      link: https://creativecommons.org/licenses/by/4.0/
      name: "CC BY 4.0 License"
  consent:
    title: "Privacy & License"
    description: "This work is licensed under a CC BY 4.0 license."
